name = "gwet"
pages_build_output_dir = "./dist"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "gwet-db"
database_id = "2fc2e771-863d-4773-a454-3d851929a240"

[vars]
JWT_SECRET = "gwet-dev-secret-change-in-production"
